### ISSUE TITLE
Attribute Error - ss_rgb

### ISSUE THREAD

**Issue by farides86** [darkscyla/MATLAB-Carla-Interface#2]
Hi, Farid here. I'm new here and new to Carla too. I just installed it but I'm facing error "Python error: AttributeError: module 'ss_rgb' has no attribute 'array' ". Please refer to attach screenshot of those error.

I couldnt find where was the problem and appreciate for your help on this. Thank you very much.

![Error](https://user-images.githubusercontent.com/41900003/114325538-85293700-9b28-11eb-97ea-5536d02bc700.JPG)

**Comment by gambiTarun** [comment]
I was facing the same issue. The problem was since I was using the newer versions of CARLA, they have added more tags to their Semantic Segmentation sensor output. This causes an indexOutOfBounds exception and prevents execution of the whole python script. This is because in "semantic_segmentation_rgb.m", the variable '_mapDict' is hardcoded for 13 tags. Just refer to the CARLA documentation and update the newly added tags in "semantic_segmentation_rgb.m".

**Comment by darkscyla** [comment]
@farides86 I know it has almost been a year since the question was asked. I apologize for not actively maintaining it. The main problem is that MATLAB license is not free outside academia. I recently got access to MATLAB again and have updated the code to reflect the changes. The solution is exactly as @tarun01 mentioned. I have now changed `_mapDict` to be of type default dict so that future additional tags do not break the code. Unknown tags shall appear white
